// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.png" {
  /**
   * A path to the PNG file
   */
  const path: `${string}.png`;
  export = path;
}

declare module "*.jpg" {
  /**
   * A path to the JPG file
   */
  const path: `${string}.jpg`;
  export = path;
}

declare module "*.jpeg" {
  /**
   * A path to the JPEG file
   */
  const path: `${string}.jpeg`;
  export = path;
}

declare module "*.gif" {
  /**
   * A path to the GIF file
   */
  const path: `${string}.gif`;
  export = path;
}

declare module "*.webp" {
  /**
   * A path to the WebP file
   */
  const path: `${string}.webp`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
